name: webcam_module
services:
  webcam_module:
    container_name: webcam_module
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:${PROJECT_VERSION}
        - ${IMAGE}:dev
    command: python webcam_module/src/webcam_rest_node.py --port 2000
    privileged: true
    env_file: .env
    volumes:
      - ${DEVICE}:/dev/video0
      - ./src:/home/app/webcam_module/src
      - ./tests:/home/app/webcam_module/tests
    ports:
      - 2000:2000
